


drop table recipient; 
DBCC CHECKIDENT('recipient', RESEED, 0);

CREATE TABLE ADMIN(
	ADMIN_ID INT identity(1,1) NOT NULL PRIMARY KEY,
	EMAIL NCHAR (50) NOT NULL,
	PASSWORD NCHAR(50) NOT NULL
)	
CREATE TABLE LOCATIONS(
	LOCATION_ID INT identity(1,1) NOT NULL PRIMARY KEY,
	LOC_NAME VARCHAR(50),
	LATITUDE FLOAT(8),
	LONGITUDE FLOAT(8)
)
CREATE TABLE DONOR  ( 
	DONOR_ID INT identity(1,1) NOT NULL PRIMARY KEY,
	EMAIL NCHAR(50) NOT NULL,
	PASSWORD NCHAR(50) NOT NULL,
	COMPANY_NAME NCHAR(50),
	LOCATION_ID INT,
	PICKUP_TIMES VARCHAR(120),
	STREET_NAME VARCHAR(120),
	ZIP CHAR(5),
	STATE_NAME CHAR(2),
	REG_STATUS CHAR(1) NOT NULL DEFAULT('D'),
	ADMIN_ID INT FOREIGN KEY REFERENCES ADMIN(ADMIN_ID)
)
CREATE TABLE PRODUCT(
	PROD_ID INT identity(1,1) NOT NULL PRIMARY KEY,
	PROD_NAME VARCHAR(50),
	PROD_SIZE VARCHAR(50), 
	PROD_STOCKQTY INT,
	PROD_CATEGORY VARCHAR(50),
	PROD_STATUS VARCHAR(50),
	EXP_DATE DATETIME2,
	DONOR_ID INT FOREIGN KEY REFERENCES DONOR(DONOR_ID)

)

CREATE TABLE RECIPIENT(
	RECIPIENT_ID INT identity(1,1) NOT NULL PRIMARY KEY,
	FIRST_NAME VARCHAR(20),
	LAST_NAME VARCHAR(20),
	EMAIL NCHAR(50),
	PHONE_NUM VARCHAR(15),
	PASSWORD VARCHAR(20),
	ZIP CHAR(5)
)
CREATE TABLE ORDERS(
	ORDER_ID INT identity(1,1) NOT NULL PRIMARY KEY,
	REC_ID INT FOREIGN KEY REFERENCES RECIPIENT(RECIPIENT_ID)
)

CREATE TABLE ORDER_ITEM_LINE(
	PRIMARY KEY CLUSTERED (PROD_ID, ORDER_ID),
	PROD_ID INT FOREIGN KEY REFERENCES PRODUCT(PROD_ID),
	ORDER_ID INT FOREIGN KEY REFERENCES ORDERS(ORDER_ID),
	
)

select * from recipient; 